### ISSUE TITLE
Arduino resetting - Looking for guidance

### ISSUE THREAD

**Issue by david-morton** [vishnumaiea/ptScheduler#6]
I'm working on an automotive project and would like to alter the frequency of my ptScheduler task (ptCalculateRpm) based on engine RPM. When I implement this as shown below the Arduino goes into a reset loop ... something is not happy.

Is this an edge case anti-pattern or am I missing something ?

The definition of the object is:
```ptScheduler ptCalculateRpm = ptScheduler(PT_TIME_200MS);```

The code that contains my desires is:
```
  if (ptCalculateRpm.call()) {
    detachInterrupt(digitalPinToInterrupt(rpmSignalPin));
    currentRpm = calculateRpm();
    attachInterrupt(digitalPinToInterrupt(rpmSignalPin), updateRpmPulse, RISING);
    // Change frequency of rpm calculation depending on RPM to avoid high error
    if (currentRpm > 1500) {
      ptCalculateRpm = ptScheduler(PT_TIME_50MS);
    } else {
      ptCalculateRpm = ptScheduler(PT_TIME_200MS);
    }
  }
```

**Comment by vishnumaiea** [comment]
Hi David. I can see one issue with your code.

```
ptCalculateRpm = ptScheduler(PT_TIME_50MS);
```

This line actually creates a new `ptScheduler` object every time you call it, which is not what you want. To change the interval of a task, you can directly change the interval variable as shown below.

```
ptCalculateRpm.sequenceList [0] = PT_TIME_50MS;
```

This alters the first interval. Depending on how many intervals you have, you can call each of them as `sequeceList[1]`, `sequeceList[2]`, etc. For a task with a single interval, you can only change `sequeceList[0]`.

The change will have an immediate effect when you call the `call()` function next time, and the effect can be unpredictable depending on how much time is already elapsed. To get a predictable behavior upon changing the interval, you can call the `reset()` function just after changing the task interval. This will reset all state and counter variables associated with the task. But the intervals will not be changed.

**Comment by david-morton** [comment]
Thanks for the prompt and excellent feedback !! All fixed now :) Using the reset caused some needle twitching as the calculation evaluated to zero and it seems quite happy without needing it ... very happy now :)

For completeness the final code snip is as below:
```
  // Check the pretty tiny scheduler tasks and call as needed
  if (ptCalculateRpm.call()) {
    detachInterrupt(digitalPinToInterrupt(rpmSignalPin));
    currentRpm = calculateRpm();
    attachInterrupt(digitalPinToInterrupt(rpmSignalPin), updateRpmPulse, RISING);
    // Change frequency of rpm calculation depending on RPM to avoid high error
    if (currentRpm >= 1500 && ptCalculateRpm.sequenceList [0] != PT_TIME_50MS) {
      ptCalculateRpm.sequenceList [0] = PT_TIME_50MS;
    } else if (currentRpm < 1500 && ptCalculateRpm.sequenceList [0] != PT_TIME_200MS) {
      ptCalculateRpm.sequenceList [0] = PT_TIME_200MS;
    }
  }
```

**Comment by vishnumaiea** [comment]
Glad it worked 😀
