### ISSUE TITLE
How to implement jitter ?

### ISSUE THREAD

**Issue by david-morton** [vishnumaiea/ptScheduler#7]
Firstly, love ptScheduler !!

I'm sending messages over serial between two Arduinos on the same schedule (say 100ms) but would like to ensure they don't all fire at the same time in a 'feast and famine' style which is hard on my receiver device.

How can I introduce a one time offset when my scheduler objects are created or similar so that i spread the load but maintain the timing of tasks ? ie: Two tasks scheduled at 100ms with a 50ms offset would result in alternating tasks triggering every 50ms.

Cheers !!

**Comment by vishnumaiea** [comment]
Hi David. Glad to hear that ptScheduler is useful to you.

Adding offset time at the beginning of a task is already supported by ptScheduler. Though this part is buried in the documentation. There are three functions that you can use to set a "skip" time (how a time offset is referred in the documentation).

`setSkipTime()` - skips the specified amount of time from the beginning.
`setSkipInterval()` - skips the amount of time calculated from the task interval list.
`setSkipSequence()` - skips the amount of time in multiple of the entire interval set.

For example, the following sketch has two tasks with the same interval value of 1 second, but offset by 0.5 second, using the setSkipTime() function before enabling it.

```cpp
#include <ptScheduler.h>

#define debugSerial Serial

ptScheduler taskOne (PT_TIME_1S);
ptScheduler taskTwo (PT_TIME_1S);

void setup() {
  debugSerial.begin (115200);

  taskOne.setSkipTime (PT_TIME_500MS);

  taskOne.enable();
  taskTwo.enable();
}

void loop() {
  if (taskOne.call()) {
    debugSerial.print ("Task 1: ");
    debugSerial.println (millis());
  }

  if (taskTwo.call()) {
    debugSerial.print ("Task 2: ");
    debugSerial.println (millis());
  }
}
```
In the following serial output, you can see that the Task 2 starts before Task 1 even though, it is the Task 1 that appears on the program first. Task 1 starts at 25 ms mark, while Task 2 starts only after a 500 ms delay, at 525 ms mark (25 + 500). So even though both tasks have the same timing interval, they run with an offset of 500 ms.

![image](https://github.com/vishnumaiea/ptScheduler/assets/10383395/7c1343f8-0751-4419-9e2b-5c21bac8df87)

Hope that helps. I will try to improve the documentation.

**Comment by david-morton** [comment]
Magic, working like a charm thankyou :)
